--DESARROLLADO POR RICHARD GARCIA ALAY
--EXTRACCION DE MARCADORES FINANCIEROS Y PROCESO DE CALCULO DE LA VARIABLE DECISION 
--DECLARACION DE VARIABLES DE Z2 ALTMAN
DECLARE @ACTIVO_CIRCULANTE AS MONEY ,
		@PASIVO_LIQUIDO AS MONEY,
		@TOTAL_ACTIVO AS MONEY,
		@X1 AS MONEY,
		@RESERVAS AS MONEY,
		@X2 AS MONEY,
		@EBIT AS MONEY,
		@X3 AS MONEY,
		@PATRIMONIO_NETO AS MONEY,
		@DEUDAS_TOTALES AS MONEY,
		@X4 AS MONEY,
		@INGRESOS_EXPLOTACION AS MONEY,
		@X5 AS MONEY,
		@A_MAXIMO AS INT,
		@A_MINIMO AS INT,
		@id_empresa AS INT,
		@DECISION AS INT,
		@CALCULO_ZALTMAN AS MONEY,
		
--DECLARACION DE VARIABLES DE INDICADORES
		@BAII AS MONEY,
	    @FONDOS_ACCIONISTAS AS MONEY,
		@INGRESOS_NETOS AS MONEY,
		@RESULTADO_OPERATIVO AS MONEY,
		@ACTIVOS_TOTALES AS MONEY,
		@ACTIVOS_PERMANENTES AS MONEY,
		@BAI AS MONEY,
		@VENTAS_TOTALES AS MONEY,
		@BENEFICIO_COMERCIAL_BRUTO AS MONEY,
		@GASTOS_FINANCIEROS AS MONEY,
		@DEUDA_TOTAL AS MONEY,
		@CAPITAL_TRABAJO_NETO AS MONEY,
		@DEUDA_IP AS MONEY,
		@EFECTIVO AS MONEY,
		@VALORES_NEGOCIABLES AS MONEY,
		@PASIVO_CORRIENTE AS MONEY,
		@ACTIVO_DISPONIBLE AS MONEY,
		@DEUDA_FINANCIERA AS MONEY,
		@FLUJO_CAJA AS MONEY,
		@INVENTARIO AS MONEY,
		@CUENTA_PENDIENTE_COBRO AS MONEY,
		@CUENTA_PENDIENTE_PAGAR AS MONEY,
				
		@RE1 AS MONEY,
		@RE2 AS MONEY,
		@RE3 AS MONEY,
		@RE4 AS MONEY,
		@RE5 AS MONEY,
		@RE6 AS MONEY,
		
		@EF2 AS MONEY,
		@EF3 AS MONEY,
		@EF4 AS MONEY,
		@EF5 AS MONEY,
		
		@PR1 AS MONEY,
			
		@SF1 AS MONEY,
		@SF2 AS MONEY,
		@SF7 AS MONEY,
		@SF8 AS MONEY,
		@SF10 AS MONEY,
		@SF11 AS MONEY,
		
		@LI1 AS MONEY,
		@LI2 AS MONEY,
		@LI3 AS MONEY,
		@LI4 AS MONEY,
		@LI5 AS MONEY,
		@LI6 AS MONEY,
		@LI7 AS MONEY,
		@LI8 AS MONEY,
		@LI9 AS MONEY,
		@LI10 AS MONEY,
		@LI11 AS MONEY,
		@LI12 AS MONEY,

		@RO1 AS MONEY,
		@RO2 AS MONEY,
		@RO3 AS MONEY,
		@RO4 AS MONEY,
		@RO5 AS MONEY,

--VARIABLES ADICIONALES PARA EL CALCULO
		@VAR_BAII_1 AS MONEY,
		@VAR_BAII_2 AS MONEY,
		@VAR_BAII_3 AS MONEY,
		@VAR_DEUDA_TOTAL_1 AS MONEY,
		@VAR_DEUDA_TOTAL_2 AS MONEY,
		@VAR_DEUDA_FINANCIERA_1 AS MONEY,
		@VAR_DEUDA_FINANCIERA_2 AS MONEY,
		@VAR_FLUJO_CAJA_1 AS MONEY,
		@VAR_FLUJO_CAJA_2 AS MONEY,
		@VAR_FLUJO_CAJA_3 AS MONEY,
		@VAR_FLUJO_CAJA_4 AS MONEY,
		@VAR_FLUJO_CAJA_5 AS MONEY
		
DECLARE CURSOR_RATIOS CURSOR
	FOR SELECT FID.id_empresa
		  -- EMP.nombre,
		  -- FID.fecha_constitucion
	FROM TABLA_FIDEICOMISOS FID JOIN TABLA_EMPRESAS EMP 
	ON FID.id_empresa=EMP.codigo
	WHERE sub_tipo_negocio='I' and estado=3 
	order by FID.id_empresa

OPEN  CURSOR_RATIOS
FETCH NEXT FROM CURSOR_RATIOS
INTO @id_empresa

WHILE @@FETCH_STATUS = 0
BEGIN
print @id_empresa
	--OBTENGO LOS AÑOS MAXIMO Y MINIMOS
	SELECT @A_MAXIMO=MAX(ANO), 
		   @A_MINIMO=MIN(ANO) 
	FROM TABLA_SALDOS
	WHERE id_empresa=@id_empresa

	IF(@A_MAXIMO=2020) SET @A_MAXIMO=2019;
	
	WHILE (@A_MINIMO<=@A_MAXIMO)
BEGIN

	--PARAMETROS PARA CALCULAR EL Z Altman

	SELECT @ACTIVO_CIRCULANTE=monto_mn_saldo 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta='101'

	SELECT @PASIVO_LIQUIDO=monto_mn_saldo 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta='20103'
		
	SELECT @TOTAL_ACTIVO=monto_mn_saldo 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta='1'

	SELECT @RESERVAS=monto_mn_saldo 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta='301'

	SELECT @EBIT=sum(monto_mn_saldo) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('402','50202')

	SELECT @PATRIMONIO_NETO=monto_mn_saldo
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('3')

	SELECT @DEUDAS_TOTALES=sum(ISNULL(monto_mn_saldo,0)) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('20107','20207')

	SELECT @INGRESOS_EXPLOTACION=monto_mn_saldo
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('401')
	
	--PARAMETROS PARA GENERAR LOS RATIOS
	SELECT @VAR_BAII_1=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('402')
	
	SELECT @VAR_BAII_2=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('50201')
	
	SELECT @VAR_BAII_3=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('50202')
	
	SET @BAII=@VAR_BAII_1-@VAR_BAII_2-@VAR_BAII_3 --BENEFICIO ANTES DE IMPUESTOS
	
	SELECT @FONDOS_ACCIONISTAS=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('301')
	
	SELECT @INGRESOS_NETOS=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('401')
	
	SET @RESULTADO_OPERATIVO=@BAII
	
	SELECT @ACTIVOS_TOTALES=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('1')

	SELECT @ACTIVOS_PERMANENTES=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('101')
	
	SELECT @BAI=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('602')
	
	SET @VENTAS_TOTALES=@INGRESOS_NETOS
	
	SELECT @BENEFICIO_COMERCIAL_BRUTO=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('402')
	
	SELECT @GASTOS_FINANCIEROS=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('50203')
	
	SELECT @VAR_DEUDA_TOTAL_1=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('201')
	
	SELECT @VAR_DEUDA_TOTAL_2=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('202')
	
	SET @DEUDA_TOTAL=@VAR_DEUDA_TOTAL_1-@VAR_DEUDA_TOTAL_2
	
	SET @CAPITAL_TRABAJO_NETO=@ACTIVOS_PERMANENTES-@VAR_DEUDA_TOTAL_1
	
	SET @DEUDA_IP=@VAR_DEUDA_TOTAL_2
	
	SELECT @EFECTIVO=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('10101')
	
	SELECT @VALORES_NEGOCIABLES=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('1010205')
	
	SELECT @PASIVO_CORRIENTE=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('201')
	
	SELECT @ACTIVO_DISPONIBLE=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('10102050201')
	
	SELECT @VAR_DEUDA_FINANCIERA_1=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('20104')
	
	SELECT @VAR_DEUDA_FINANCIERA_2=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('20203')
	
	SET @DEUDA_FINANCIERA=@VAR_DEUDA_FINANCIERA_1+@VAR_DEUDA_FINANCIERA_2
	
	SELECT @VAR_FLUJO_CAJA_1=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('801')
	
	SELECT @VAR_FLUJO_CAJA_2=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('5020221')
	
	SELECT @VAR_FLUJO_CAJA_3=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('1010205')
	
	SELECT @VAR_FLUJO_CAJA_4=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('20103')
	
	SELECT @VAR_FLUJO_CAJA_5=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('20202')
	
	SET @FLUJO_CAJA=@VAR_FLUJO_CAJA_1-@VAR_FLUJO_CAJA_2+@VAR_FLUJO_CAJA_3-(@VAR_FLUJO_CAJA_4+@VAR_FLUJO_CAJA_5)
	
	SELECT @INVENTARIO=ISNULL(monto_mn_saldo,0) 
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('10103')
	
	SELECT @CUENTA_PENDIENTE_COBRO=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('1010205')
	
	SET @CUENTA_PENDIENTE_PAGAR= (@VAR_FLUJO_CAJA_4+@VAR_FLUJO_CAJA_5)
	
	SELECT @ACTIVO_CIRCULANTE=ISNULL(monto_mn_saldo,0)
	FROM  dbo.TABLA_SALDOS 
	WHERE id_empresa=@id_empresa AND mes=12 AND ano=@A_MINIMO AND codigo_cuenta in('101')
	
	--INDICADRES DE RENTABILIDAD
	IF @FONDOS_ACCIONISTAS=0	SET @RE1=0 ELSE SET @RE1=@BAII/@FONDOS_ACCIONISTAS
	IF @FONDOS_ACCIONISTAS=0	SET @RE2=0 ELSE SET @RE2=@INGRESOS_NETOS/@FONDOS_ACCIONISTAS
	IF @ACTIVOS_TOTALES=0		SET @RE3=0 ELSE SET @RE3=@RESULTADO_OPERATIVO/@ACTIVOS_TOTALES
	IF @ACTIVOS_PERMANENTES=0	SET @RE4=0 ELSE SET @RE4=@RESULTADO_OPERATIVO/@ACTIVOS_PERMANENTES
	IF @ACTIVOS_TOTALES=0		SET @RE5=0 ELSE SET @RE5=@BAI/@ACTIVOS_TOTALES
	IF @ACTIVOS_TOTALES=0		SET @RE6=0 ELSE SET @RE6=@INGRESOS_NETOS/@ACTIVOS_TOTALES
	
	--INDICADORES DE EFICIENCIA
	IF @FONDOS_ACCIONISTAS=0 SET @EF2=0 ELSE SET @EF2=@VENTAS_TOTALES/@FONDOS_ACCIONISTAS
	IF @VENTAS_TOTALES=0	 SET @EF3=0 ELSE SET @EF3=@BAI/@VENTAS_TOTALES
	IF @ACTIVOS_TOTALES=0	 SET @EF4=0 ELSE SET @EF4=@VENTAS_TOTALES/@ACTIVOS_TOTALES
	IF @VENTAS_TOTALES=0	 SET @EF5=0 ELSE SET @EF5=@BENEFICIO_COMERCIAL_BRUTO/@VENTAS_TOTALES
			
	--INDICADORES DE PROBLEMAS FINANCIEROS
	IF @VENTAS_TOTALES=0 SET @PR1=0 ELSE SET @PR1=@GASTOS_FINANCIEROS/@VENTAS_TOTALES
	
	--INDICADODRES DE ESCTRUCTIRA FINANCIERA
	IF @ACTIVOS_TOTALES=0	 SET @SF1=0 ELSE SET @SF1=@FONDOS_ACCIONISTAS/@ACTIVOS_TOTALES
	IF @FONDOS_ACCIONISTAS=0 SET @SF2=0 ELSE SET @SF2=@DEUDA_TOTAL/@FONDOS_ACCIONISTAS
	IF @ACTIVOS_TOTALES=0	 SET @SF7=0 ELSE SET @SF7=@DEUDA_TOTAL/@ACTIVOS_TOTALES
	IF @ACTIVOS_TOTALES=0	 SET @SF8=0 ELSE SET @SF8=@CAPITAL_TRABAJO_NETO/@ACTIVOS_TOTALES
	IF @DEUDA_TOTAL=0		 SET @SF10=0 ELSE SET @SF10=@DEUDA_IP/@DEUDA_TOTAL
	IF @FONDOS_ACCIONISTAS=0 SET @SF11=0 ELSE SET @SF11=@DEUDA_IP/@FONDOS_ACCIONISTAS
		
	--INDICADORES DE LIQUIDEZ
	IF @ACTIVOS_TOTALES=0		SET @LI1=0 ELSE SET @LI1=@EFECTIVO+@VALORES_NEGOCIABLES/@ACTIVOS_TOTALES
	IF @ACTIVOS_TOTALES=0		SET @LI2=0 ELSE SET @LI2=@EFECTIVO/@ACTIVOS_TOTALES
	IF @VENTAS_TOTALES=0		SET @LI3=0 ELSE SET @LI3=@EFECTIVO+@VALORES_NEGOCIABLES/@VENTAS_TOTALES
	IF @PASIVO_CORRIENTE=0		SET @LI4=0 ELSE SET @LI4=@EFECTIVO+@VALORES_NEGOCIABLES+@ACTIVO_DISPONIBLE/@PASIVO_CORRIENTE
	IF @PASIVO_CORRIENTE=0		SET @LI5=0 ELSE SET @LI5=@EFECTIVO/@PASIVO_CORRIENTE
	IF @PASIVO_CORRIENTE=0		SET @LI6=0 ELSE SET @LI6=@ACTIVO_CIRCULANTE/@PASIVO_CORRIENTE
	IF @VENTAS_TOTALES=0		SET @LI7=0 ELSE SET @LI7=@ACTIVO_DISPONIBLE/@VENTAS_TOTALES
	IF @ACTIVOS_TOTALES=0		SET @LI8=0 ELSE SET @LI8=@PASIVO_CORRIENTE/@ACTIVOS_TOTALES
	IF @ACTIVOS_TOTALES=0		SET @LI9=0 ELSE SET @LI9=@ACTIVO_DISPONIBLE/@ACTIVOS_TOTALES
	IF @VENTAS_TOTALES=0		SET @LI10=0 ELSE SET @LI10=@RESULTADO_OPERATIVO/@VENTAS_TOTALES
	IF @FLUJO_CAJA=0			SET @LI11=0 ELSE SET @LI11=@DEUDA_FINANCIERA/@FLUJO_CAJA
	IF @DEUDA_TOTAL=0			SET @LI12=0 ELSE SET @LI12=@EFECTIVO/@DEUDA_TOTAL
	
	--INDICADORES DE ROTACION
	IF @VENTAS_TOTALES=0 SET @RO1=0 ELSE SET @RO1=@EFECTIVO/@VENTAS_TOTALES
	IF @VENTAS_TOTALES=0 SET @RO2=0 ELSE SET @RO2=@INVENTARIO/@VENTAS_TOTALES
	IF @VENTAS_TOTALES=0 SET @RO3=0 ELSE SET @RO3=@CAPITAL_TRABAJO_NETO/@VENTAS_TOTALES
	IF @VENTAS_TOTALES=0 SET @RO4=0 ELSE SET @RO4=@CUENTA_PENDIENTE_COBRO/@VENTAS_TOTALES
	IF @VENTAS_TOTALES=0 SET @RO5=0 ELSE SET @RO5=@CUENTA_PENDIENTE_PAGAR/@VENTAS_TOTALES
	
		--PROCESO PARA GENERAR LOS RATIOS FINANCIEROS
	--ECUACION Z2-ALTMAN PARA PREDECIR SI EXISTE QUIEBRA DE PROYECTO
	--Z2-ALTMAN=  6,56*X1 + 3,26*X2 + 6,72*X3 + 1,05*X4 
	----EMPRESA CAPITAL CERRADO	
	----MANUFACTURA
	----<1,10  ZONA DE QUIEBRA
	---->2,60 ZONA DE NO QUIEBRA 
	--X1 = (Activo circulante (101) – Pasivo líquido(20103)) / Total activo (1)
	--X2 = Reservas (301) / Total activo (1)
	--X3 = EBIT (402 + 50202) / Total activo (1)
	--X4 = Patrimonio neto(3) / Deudas totales (20107 + 20207)
	--X5 = Ingresos de explotación (401) / Total activo (1)
	
	
	
	IF(@TOTAL_ACTIVO=0) SET @X1=0 ELSE SET @X1=(@ACTIVO_CIRCULANTE-@PASIVO_LIQUIDO)/@TOTAL_ACTIVO;
	IF(@TOTAL_ACTIVO=0) SET @X2=0 ELSE SET @X2=@RESERVAS/@TOTAL_ACTIVO;
	IF(@TOTAL_ACTIVO=0) SET @X3=0 ELSE SET @X3=@EBIT/@TOTAL_ACTIVO;
	IF(@DEUDAS_TOTALES=0) SET @X4=0 ELSE SET @X4=@PATRIMONIO_NETO/@DEUDAS_TOTALES;
	IF(@TOTAL_ACTIVO=0) SET @X5=0 ELSE SET @X5=@INGRESOS_EXPLOTACION/@TOTAL_ACTIVO;
	
	--ECUACION Z-ALTMAN
	SET @CALCULO_ZALTMAN=6.56*@X1 + 3.26*@X2 + 6.72*@X3 + 1.05*@X4;
	
	IF @CALCULO_ZALTMAN<1.10
		SET @DECISION=0 --QUIEBRA 
	ELSE
		SET @DECISION=1 --NO QUIEBRA
		
	INSERT INTO TFM_DATOS_GENERAR_RATIOS
	(codigoEmpresa,
	 anio,
	 mes,
	 activo_circulante,
	 pasivo_liquido,
	 total_activo,
	 reservas,
	 ebit,
	 patrimonio_neto,
	 deudas_totales,
	 ingresos_explotacion,
	 pasivo_circulante,
	 
	 RE1,
	 RE2,
	 RE3,
	 RE4,
	 RE5,
	 RE6,
	 EF2,
	 EF3,
	 EF4,
	 EF5,
	 PR1,
	 SF1,
	 SF2,
	 SF7,
	 SF8,
	 SF10,
	 SF11,
	 LI1,
	 LI2,
	 LI3,
	 LI4,
	 LI5,
	 LI6,
	 LI7,
	 LI8,
	 LI9,
	 LI10,
	 LI11,
	 LI12,
	 RO1,
	 RO2,
	 RO3,
	 RO4,
	 RO5,
  
	 x1,
	 x2,
	 x3,
	 x4,
	 x5,
	 decision,
	 usuario_genera,
	 fecha_genera)VALUES(@id_empresa,
			   @A_MINIMO,
			   12,
			   @ACTIVO_CIRCULANTE,
			   @PASIVO_LIQUIDO,
			   @TOTAL_ACTIVO,
			   @RESERVAS,
			   @EBIT,
			   @PATRIMONIO_NETO,
			   @DEUDAS_TOTALES,
			   @INGRESOS_EXPLOTACION,
			   @PASIVO_CORRIENTE,
				   
				@RE1,
				@RE2,
				@RE3,
				@RE4,
				@RE5,
				@RE6,
				@EF2,
				@EF3,
				@EF4,
				@EF5,
				@PR1,
				@SF1,
				@SF2,
				@SF7,
				@SF8,
				@SF10,
				@SF11,
				@LI1,
				@LI2,
				@LI3,
				@LI4,
				@LI5,
				@LI6,
				@LI7,
				@LI8,
				@LI9,
				@LI10,
				@LI11,
				@LI12,
				@RO1,
				@RO2,
				@RO3,
				@RO4,
				@RO5,

			   @X1,
			   @X2,
			   @X3,
			   @X4,
			   @X5,
			   @DECISION,
			   'USUARIO',
			   GETDATE())
	
	SET @A_MINIMO=@A_MINIMO+1;
	
	
END 


FETCH NEXT FROM CURSOR_RATIOS
INTO @id_empresa
END 
CLOSE CURSOR_RATIOS
DEALLOCATE CURSOR_RATIOS
		
SELECT *FROM TFM_DATOS_GENERAR_RATIOS WHERE decision=0
SELECT *FROM TFM_DATOS_GENERAR_RATIOS
